name: Release
on:
  push:
    branches: [master]
jobs:
  production-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install modules
        run: yarn

      - name: Run build
        run: yarn run build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release
          npm run version
