name: Release

on:
  push:
    branches: [master]

jobs:
  production-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install modules
        run: pnpm install

      - name: Run build
        run: pnpm run build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run release
